package chat.users.permission;

public enum Permission
{
    SEND_MESSAGE,
    RECEIVE_MESSAGE,
    DELETE_MESSAGE,
    EDIT_MESSAGE,
    MODERATE_MESSAGE,
    ADD_USER,
    EDIT_USER,
    DELETE_USER,
    BAN_USER,
    WARN_USER,
    CREATE_CHATROOM,
    ENTER_CHATROOM,
    LEAVE_CHATROOM,
    DELETE_CHATROOM,
    EDIT_CHATROOM,
    VIEW_PROFILE,
    EDIT_PROFILE,
    UPLOAD_FILE,
    DOWNLOAD_FILE
}
